import Head from 'next/head'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'

export default function Home({ results }) {
  return (
    <main>
      <Head>
        <title>Movie Search App by Pacio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/movieicon.png" />
      </Head>

      <Header />
      <Nav />
      <Results results={results} />

    </main>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`)
  .then(res => res.json());

  return {
    props: {
      results: request.results
    }
  }
} 